### ISSUE TITLE
[BUG] wrong digest algorithm OID in DigestInfo

### ISSUE THREAD

**Issue by kjur** [Harzu/wasm-rsa#14]
Thank you for your great module. I found a bug in signature creation and verification.

In signature generation, This will calculate a hash value of message with SHA256.
https://github.com/Harzu/wasm-rsa/blob/2647e65b66db5d55d7051c4a37cae56aed627e5c/src/lib/private_keys.rs#L67
However hash algorithm OID in DigestInfo is specified as SHA3_256 by mistake. This shall be SHA256.
https://github.com/Harzu/wasm-rsa/blob/2647e65b66db5d55d7051c4a37cae56aed627e5c/src/lib/private_keys.rs#L71

There is the same issue in signature verification:
https://github.com/Harzu/wasm-rsa/blob/2647e65b66db5d55d7051c4a37cae56aed627e5c/src/lib/public_keys.rs#L63
This also shall be SHA256 not SHA3_256:
https://github.com/Harzu/wasm-rsa/blob/2647e65b66db5d55d7051c4a37cae56aed627e5c/src/lib/public_keys.rs#L67

This bug will cause mismatch between algorithm OID and hash value in DigestInfo and raise interoperability issue with other crypto library such like OpenSSL.
I have less knowledge of Rust to fix this. Could you fix this? Thank you for your help.

**Comment by Harzu** [comment]
Hey! Thanks for the issue. I will be doing this soon

**Comment by kjur** [comment]
Thank you for the fix.
