### ISSUE TITLE
can't resolve './rsa_lib_bg'

### ISSUE THREAD

**Issue by luanwulin** [Harzu/wasm-rsa#9]
in browser mode, the rsa_lib_bg.js file is missing
version:0.3.2
webpack:4.40.2

**Comment by Harzu** [comment]
@luanwulin 

I updated the dependencies and checked the [webpack_four](https://github.com/Harzu/wasm-rsa/tree/master/examples/webpack_four) examples
it works!
it might be worth upgrading to 0.3.3 and try again
